### ISSUE TITLE
weather.sh error

### ISSUE THREAD

**Issue by yuceltoluyag** [edbizarro/dotfiles#6]
weather.sh: line 14: jq: command not found
  °C

**Comment by edbizarro** [comment]
hi @yuceltoluyag 

Tks for reporting, You need to install the `jq` package, if you're on arch: https://www.archlinux.org/packages/community/x86_64/jq

I'll include this on readme

**Comment by yuceltoluyag** [comment]
sorry I did not see much work at night :(
